apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-poc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-poc-app
  template:
    metadata:
      labels:
        app: my-poc-app
    spec:
      containers:
      - name: my-poc/app
        image: jayantvats/webapp:latest
        ports:
        - containerPort: 80
